'use client';

import { useState, useEffect } from 'react';
import { ChevronLeft, ChevronRight, Share2, Download } from 'lucide-react';
import dayjs from 'dayjs';
import { getStudents } from '@/services/students';
import { getMonthlyAttendanceAllStudents } from '@/services/attendance';
import { useToast } from '@/components/ui/Toast';

function Avatar({ name, size = 36 }: { name: string; size?: number }) {
  const colors = ['#6C63FF','#4CAF50','#F44336','#FF9800','#2196F3','#9C27B0','#00BCD4','#FF5722'];
  const color = colors[name.charCodeAt(0) % colors.length];
  return <div style={{ width: size, height: size, backgroundColor: color, borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white', fontSize: size * 0.38, fontWeight: 700, flexShrink: 0 }}>{name.slice(0, 2).toUpperCase()}</div>;
}

export default function AttendanceReportPage() {
  const [month, setMonth] = useState(dayjs());
  const { toast } = useToast();
  const [report, setReport] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => { load(); }, [month]);

  const load = async () => {
    setLoading(true);
    try {
      const [students, summaries] = await Promise.all([getStudents(), getMonthlyAttendanceAllStudents(month.year(), month.month() + 1)]);
      const result = students.map((s: any) => {
        const summary = (summaries as any)[s.id] ?? { present: 0, absent: 0, leave: 0, total: 0 };
        const pct = summary.total > 0 ? Math.round(summary.present / summary.total * 100) : 0;
        return { ...s, ...summary, pct };
      });
      setReport(result.sort((a: any, b: any) => b.pct - a.pct));
    } catch (e) { console.error(e); }
    finally { setLoading(false); }
  };

  const handleExportExcel = async () => {
    const XLSX = await import('xlsx');
    const wsData = [
      ['Attendance Report — ' + month.format('MMMM YYYY')],
      [],
      ['#', 'Name', 'Grade', 'Present', 'Absent', 'Leave', 'Total', 'Attendance %'],
      ...report.map((s: any, i: number) => [i + 1, s.name, s.grade, s.present, s.absent, s.leave, s.total, `${s.pct}%`]),
      [],
      ['', 'Average', '', '', '', '', '', `${avgPct}%`],
    ];
    const ws = XLSX.utils.aoa_to_sheet(wsData);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Attendance');
    XLSX.writeFile(wb, `Attendance_${month.format('MMMM_YYYY')}.xlsx`);
  };

  const handleShare = async () => {
    const lines = [`Attendance Report — ${month.format('MMMM YYYY')}`, `Generated by Genix Connect`, '', ...report.map((s: any) => `${s.name} (${s.grade}): ${s.present}P ${s.absent}A ${s.leave}L — ${s.pct}%`)];
    await navigator.share?.({ text: lines.join('\n') }) ?? navigator.clipboard.writeText(lines.join('\n'));
    toast('Report copied to clipboard!', 'success');
  };

  const avgPct = report.length > 0 ? Math.round(report.reduce((a: number, s: any) => a + s.pct, 0) / report.length) : 0;
  const below75 = report.filter((s: any) => s.pct < 75).length;

  return (
    <div className="p-4 md:p-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center gap-3 mb-5">
        <h1 className="text-2xl font-bold text-gray-900">Attendance Report</h1>
        <div className="flex items-center gap-2 flex-wrap sm:ml-auto">
          <div className="flex items-center gap-2 bg-white border border-gray-200 rounded-lg px-3 py-2">
            <button onClick={() => setMonth(month.subtract(1, 'month'))} className="hover:text-[#6C63FF]"><ChevronLeft className="w-4 h-4" /></button>
            <span className="text-sm font-semibold text-gray-800 min-w-28 text-center">{month.format('MMMM YYYY')}</span>
            <button onClick={() => setMonth(month.add(1, 'month'))} disabled={month.isSame(dayjs(), 'month')} className="hover:text-[#6C63FF] disabled:opacity-30"><ChevronRight className="w-4 h-4" /></button>
          </div>
          <button onClick={handleExportExcel} disabled={loading || report.length === 0} className="flex items-center gap-1.5 border border-green-500 text-green-600 px-3 py-2 rounded-lg text-sm font-medium hover:bg-green-50 disabled:opacity-40">
            <Download className="w-4 h-4" /> Export Excel
          </button>
          <button onClick={handleShare} disabled={loading || report.length === 0} className="flex items-center gap-1.5 border border-gray-200 px-3 py-2 rounded-lg text-sm font-medium text-gray-600 hover:bg-gray-50 disabled:opacity-40">
            <Share2 className="w-4 h-4" /> Share
          </button>
        </div>
      </div>

      {!loading && report.length > 0 && (
        <div className="grid grid-cols-3 gap-3 mb-5">
          {[['Students', report.length, '#6C63FF'], ['Avg Attendance', `${avgPct}%`, avgPct >= 75 ? '#4CAF50' : '#F44336'], ['Below 75%', below75, '#F44336']].map(([label, value, color]) => (
            <div key={String(label)} className="bg-white rounded-xl p-3 shadow-sm border border-gray-100 text-center">
              <p className="text-xl md:text-2xl font-bold" style={{ color: String(color) }}>{value}</p>
              <p className="text-xs text-gray-500 mt-0.5">{label}</p>
            </div>
          ))}
        </div>
      )}

      {/* Desktop table */}
      <div className="hidden md:block bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        <table className="w-full">
          <thead className="bg-gray-50 border-b border-gray-100">
            <tr>{['#', 'Student', 'Grade', 'Present', 'Absent', 'Leave', 'Attendance %'].map(h => <th key={h} className="text-left px-5 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wide">{h}</th>)}</tr>
          </thead>
          <tbody>
            {loading ? <tr><td colSpan={7} className="text-center py-12 text-gray-400">Loading report...</td></tr> :
              report.map((s: any, i: number) => (
                <tr key={s.id} className="border-b border-gray-50 hover:bg-gray-50">
                  <td className="px-5 py-3 text-xs text-gray-400">#{i + 1}</td>
                  <td className="px-5 py-3"><div className="flex items-center gap-3"><Avatar name={s.name} size={32} /><span className="font-medium text-gray-800 text-sm">{s.name}</span></div></td>
                  <td className="px-5 py-3 text-sm text-gray-500">{s.grade}</td>
                  <td className="px-5 py-3 text-sm font-semibold text-green-600">{s.present}</td>
                  <td className="px-5 py-3 text-sm font-semibold text-red-500">{s.absent}</td>
                  <td className="px-5 py-3 text-sm font-semibold text-amber-500">{s.leave}</td>
                  <td className="px-5 py-3">
                    <div className="flex items-center gap-3">
                      <div className="flex-1 bg-gray-100 rounded-full h-2 max-w-24">
                        <div className="h-2 rounded-full" style={{ width: `${s.pct}%`, backgroundColor: s.pct >= 75 ? '#4CAF50' : '#F44336' }} />
                      </div>
                      <span className={`text-sm font-bold min-w-12 ${s.pct >= 75 ? 'text-green-600' : 'text-red-500'}`}>{s.pct}%</span>
                    </div>
                  </td>
                </tr>
              ))
            }
          </tbody>
        </table>
      </div>

      {/* Mobile cards */}
      <div className="md:hidden space-y-2">
        {loading ? <div className="bg-white rounded-xl p-8 text-center text-gray-400">Loading report...</div> :
          report.map((s: any, i: number) => (
            <div key={s.id} className="bg-white rounded-xl p-4 shadow-sm border border-gray-100">
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-3">
                  <Avatar name={s.name} size={36} />
                  <div>
                    <p className="font-semibold text-gray-800 text-sm">#{i + 1} {s.name}</p>
                    <p className="text-xs text-gray-400">{s.grade}</p>
                  </div>
                </div>
                <span className={`text-lg font-bold ${s.pct >= 75 ? 'text-green-600' : 'text-red-500'}`}>{s.pct}%</span>
              </div>
              <div className="w-full bg-gray-100 rounded-full h-1.5 mb-2">
                <div className="h-1.5 rounded-full" style={{ width: `${s.pct}%`, backgroundColor: s.pct >= 75 ? '#4CAF50' : '#F44336' }} />
              </div>
              <div className="flex gap-4 text-xs">
                <span className="text-green-600 font-semibold">{s.present} Present</span>
                <span className="text-red-500 font-semibold">{s.absent} Absent</span>
                <span className="text-amber-500 font-semibold">{s.leave} Leave</span>
              </div>
            </div>
          ))
        }
      </div>
    </div>
  );
}
